Import('env')
bin_env = env.Clone()

# Build test binary
executable_files = ['main.cpp']

bin_env.Append(LIBS = ['FlightlessManicotti'])

executable = bin_env.Program('FlightlessManicotti', executable_files)

Return('executable')
