Import('env')
bin_env = env.Clone()

# Build test binary
executable_files = ['main.cpp']

executable = bin_env.Program('FlightlessManicotti',
   executable_files,
   CPPPATH = [] + env['KL_INCPATH'],
   CXXFLAGS = ['-g'] + env['CCFLAGS'],
   LIBS=['FlightlessManicotti'], 
   LIBPATH=[] + env['KL_LIBPATH']
)
Return('executable')