from SCons.Util import flatten
import os

Import('env')
coreEnv = env.Clone()

# Files used for library
lib_files = ['etc/all.c']

core_lib = coreEnv.StaticLibrary('lua', 
	lib_files,
	CPPPATH = ['.','src'],
	CCFLAGS = [],
	LIBS=[], 
	LIBPATH=['.']
)

Return(['core_lib'])