# Ziggurat -- Copyright 2011 GameClay LLC
# Portions Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env')
import os

# Common Darwin build settings
env.Append(CPPDEFINES=[env['ZIG_OS_DARWIN']])

env.Append(CPPFLAGS=['-pipe'])

ccld = ['-mmacosx-version-min=10.7']
env.Append(CXXFLAGS=ccld)
env.Append(CFLAGS=ccld)
env.Append(LINKFLAGS=ccld)

# Use CLANG
env['AR'] = 'ar'
env['CC'] = 'clang'
env['CXX'] = 'clang++'
env['LINK'] = 'clang'
