import os, sys, platform

Import("env")

# Build the library
if env['NEDMALLOC_STATIC_LIB']:
    nedmalloclib = env.StaticLibrary(env['NEDMALLOC_LIBRARYNAME'], 
        source = ['nedmalloc.c'], 
        CPPPATH = ['.'],
        CPPDEFINES=env['NEDMALLOCCPPDEFINES']+["NEDMALLOC_DLL_EXPORTS"], 
        CCFLAGS=env['CCFLAGS']+env['CCFLAGSFORNEDMALLOC']
    )
else:
    libobjects = env.SharedObject("nedmalloc.c", CPPPATH=[","], CPPDEFINES=env['NEDMALLOCCPPDEFINES']+["NEDMALLOC_DLL_EXPORTS"], CCFLAGS=env['CCFLAGS']+env['CCFLAGSFORNEDMALLOC'])
    if sys.platform=='win32':
        libobjects+=env.SharedObject("winpatcher.c", CPPDEFINES=env['NEDMALLOCCPPDEFINES']+["NEDMALLOC_DLL_EXPORTS"])
        libobjects+=env.RES("nedmalloc.res", "nedmalloc_dll.rc")
    nedmalloclib = env.SharedLibrary(env['NEDMALLOC_LIBRARYNAME'], source = libobjects)
    if sys.platform=='win32': env.AddPostAction(nedmalloclib, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')
nedmallocliblib = nedmalloclib
if sys.platform=='win32':
    #env.AddPreAction(env.AddPreAction(nedmalloclib, "pgomgr /clear ${VARIANT}/nedmalloc.pgd"), "pgomgr /merge ${VARIANT}/nedmalloc.pgd")
    nedmallocliblib=nedmalloclib[1]

# Test program
if not env['NEDMALLOC_NO_TESTS']:
    sources = [ "test.c" ]
    objects = env.Object(source = sources) # + [nedmallocliblib]
    testlibs=[nedmallocliblib]
    testprogram = env.Program("test", source = objects, LINKFLAGS=[], LIBS = testlibs)

    # PGO program
    sources = [ "make_pgos.c" ]
    objects = env.Object(source = sources) # + [nedmallocliblib]
    testlibs=[nedmallocliblib]
    testprogram = env.Program("make_pgos", source = objects, LINKFLAGS=[], LIBS = testlibs)

    Default(testprogram)

Return("nedmalloclib")
